In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model
from tensorflow.keras.initializers import HeNormal, RandomNormal
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import matplotlib
from sklearn.model_selection import train_test_split

In [3]:
print(matplotlib.__version__)
print(tf.__version__)

3.7.1
2.10.0


In [4]:
def load_image_paths_by_class(dataset_path):
    
    #สร้าง dictionary 
    class_image_paths = {}

    for class_name in os.listdir(dataset_path): #os.listdir ดึงรายชื่อไฟล์/โฟเดอร์ใน paht
        class_dir = os.path.join(dataset_path, class_name)#os.path.join = images\photo.jpg
        #print(class_dir)
        if os.path.isdir(class_dir):#ตรวจสอบclass_dir เป็นโฟลเดอร์ถ้าเป็นโฟลเดอร์ จะเข้าไปทำงานต่อ
            image_files = [ 
                os.path.join(class_dir, img) #
                for img in os.listdir(class_dir) # ดึงรายชื่อ
                if img.lower().endswith(('.jpg', '.jpeg', '.png')) #
            ]
            if len(image_files) >= 20:  # ขั้นต่ำ 3 ภาพผป
                class_image_paths[class_name] = image_files # สร้าง dictionary

    return class_image_paths


In [5]:
#dataset_path = r'C:\InceptionNet\mediamdata' 
dataset_path3 = r"D:\InceptionNet\GLint360K\glint360k_3"
dic = load_image_paths_by_class(dataset_path3)
print(len(dic))
#print(dictm)


11023


In [6]:
classes = list(dic.keys())
#print(classes)
#print(len(classes))

In [10]:
train_classes, val_classes = train_test_split(classes, test_size=0.2, random_state=42)

print(f"จำนวนคลาสสำหรับ Training: {len(train_classes)}")
print(f"จำนวนคลาสสำหรับ Validation: {len(val_classes)}")


จำนวนคลาสสำหรับ Training: 8818
จำนวนคลาสสำหรับ Validation: 2205


In [11]:
train_image_dict1 = {
    class_name: dic[class_name]
    for class_name in train_classes
}

# สร้าง dictionary สำหรับ Validation
val_image_dict1 = {
    class_name: dic[class_name]
    for class_name in val_classes
}
print(f"ขนาดของ Dictionary สำหรับ Training: {len(train_image_dict1)}")
print(f"ขนาดของ Dictionary สำหรับ Validation: {len(val_image_dict1)}")



ขนาดของ Dictionary สำหรับ Training: 8818
ขนาดของ Dictionary สำหรับ Validation: 2205


In [ ]:
#print("\n--- รายชื่อคลาสสำหรับ Training ---")
#for class_name in train_classes:
    #print(class_name)

# ---
# ปริ้นชื่อคลาสสำหรับ Validation
print("\n--- รายชื่อคลาสสำหรับ Validation ---")
for class_name in val_classes:
    print(class_name)

In [9]:
def loadimage(image_path):
    try:
        img = tf.io.read_file(image_path)
        img = tf.image.decode_jpeg(img, channels=3)
        img = tf.image.resize(img, (224, 224))
        img = tf.cast(img, tf.float32)
        img = img / 255.0  # Normalization
        img = tf.clip_by_value(img, 0.0, 1.0)#img = tf.where(tf.math.is_finite(img), img, tf.zeros_like(img)) # แทนที่ค่า NaN หรือ Inf ด้วย 0
        img.set_shape((224, 224, 3))
        return img
    except:
        print(f"Error loading image {image_path}. Returning a zero tensor.")
        return tf.zeros((224, 224, 3), dtype=tf.float32)
    
    

Online Triplet Mining

In [12]:
import random
def triplet_generator(image_dict, num_triplets_per_epoch):
    # image_dict คือ dictionary ของคุณที่ได้จากขั้นตอนที่ 1
    # num_triplets_per_epoch คือจำนวน triplet ที่ต้องการใน 1 รอบ (epoch)
    classes = list(image_dict.keys()) # ดึงชื่อคลาสทั้งหมด
    for _ in range(num_triplets_per_epoch):
        # 1. สุ่ม anchor และ positive จากคลาสเดียวกัน
        anchor_class = random.choice(classes)
        # ตรวจสอบว่าคลาสนั้นมีรูปภาพอย่างน้อย 2 รูป
        if len(image_dict[anchor_class]) < 2:
            continue

        a, p = random.sample(image_dict[anchor_class], 2)
        
        # 2. สุ่ม negative จากคลาสอื่น
        neg_classes = [c for c in classes if c != anchor_class]
        if not neg_classes:
            continue
            
        negative_class = random.choice(neg_classes)
        n = random.choice(image_dict[negative_class])
        
        # คืนค่า (yield) Path ของรูปภาพ
        yield (a, p, n)
        

Hard Negative

Semi-Hard Negative

In [13]:
def builddataset1(image_dict, num_triplets, batch_size):
    dataset = tf.data.Dataset.from_generator(
        lambda: triplet_generator(image_dict, num_triplets),
        output_signature=(
            tf.TensorSpec(shape=(), dtype=tf.string),
            tf.TensorSpec(shape=(), dtype=tf.string),
            tf.TensorSpec(shape=(), dtype=tf.string)
        )
    )
    dataset = dataset.map(
        lambda a, p, n: (loadimage(a), loadimage(p), loadimage(n)),
        num_parallel_calls=tf.data.AUTOTUNE
    )
    dataset = dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE) #เพิ่มมิติ btach
    return dataset

triple = 50000
BATCH_SIZE = 4

train_dataset = builddataset1(train_image_dict1, triple, BATCH_SIZE)
val_dataset = builddataset1(val_image_dict1, int(triple*0.1), BATCH_SIZE)

In [50]:
l = 0

# ทดสอบ
for a, p, n in train_dataset.take(5):
    print("Anchor batch shape:", a.shape)
    print("Positive batch shape:", p.shape)
    print("Negative batch shape:", n.shape)
    print("ลูปที่:", a)
    #l = l + 1Q
    print("ลูปที่:", l)

Anchor batch shape: (4, 224, 224, 3)
Positive batch shape: (4, 224, 224, 3)
Negative batch shape: (4, 224, 224, 3)
ลูปที่: tf.Tensor(
[[[[0.12156863 0.14117648 0.02352941]
   [0.12941177 0.14901961 0.03137255]
   [0.14509805 0.16470589 0.04705882]
   ...
   [0.85490197 0.8509804  0.83137256]
   [0.9254902  0.92156863 0.9019608 ]
   [0.9607843  0.95686275 0.9372549 ]]

  [[0.12745099 0.14705883 0.02941176]
   [0.13480392 0.15441176 0.03676471]
   [0.1495098  0.16911764 0.05147059]
   ...
   [0.8490196  0.845098   0.8254902 ]
   [0.9235294  0.9196078  0.9       ]
   [0.9607843  0.95686275 0.9372549 ]]

  [[0.1392157  0.15882353 0.04117647]
   [0.14558823 0.16519608 0.04754902]
   [0.15833333 0.17794117 0.06029412]
   ...
   [0.8372549  0.8333333  0.8137255 ]
   [0.9196078  0.91568625 0.8960784 ]
   [0.9607843  0.95686275 0.9372549 ]]

  ...

  [[0.7892157  0.7852941  0.70686275]
   [0.7742647  0.7703431  0.69191176]
   [0.7443628  0.7404412  0.6620098 ]
   ...
   [0.38602942 0.24485295 0

In [14]:
import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Lambda, Input,Dropout

In [15]:

def QQQ():
    input_shape = (224, 224, 3)

    base_model = ResNet50(
        include_top=False,
        weights='imagenet',
        input_shape=input_shape
    )
    for layer in base_model.layers:
        layer.trainable = False
        
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(128)(x)
    embedding = Lambda(lambda x: tf.math.l2_normalize(x, axis=1))(x)
    
    # สร้างโมเดลและ return
    model = Model(inputs=base_model.input, outputs=embedding)
    
    return model

In [18]:
model = QQQ()
model.summary()

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_5[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                            

In [19]:
for i, layer in enumerate(model.layers):
    print(i, layer.name, layer.trainable)


0 input_5 False
1 conv1_pad False
2 conv1_conv False
3 conv1_bn False
4 conv1_relu False
5 pool1_pad False
6 pool1_pool False
7 conv2_block1_1_conv False
8 conv2_block1_1_bn False
9 conv2_block1_1_relu False
10 conv2_block1_2_conv False
11 conv2_block1_2_bn False
12 conv2_block1_2_relu False
13 conv2_block1_0_conv False
14 conv2_block1_3_conv False
15 conv2_block1_0_bn False
16 conv2_block1_3_bn False
17 conv2_block1_add False
18 conv2_block1_out False
19 conv2_block2_1_conv False
20 conv2_block2_1_bn False
21 conv2_block2_1_relu False
22 conv2_block2_2_conv False
23 conv2_block2_2_bn False
24 conv2_block2_2_relu False
25 conv2_block2_3_conv False
26 conv2_block2_3_bn False
27 conv2_block2_add False
28 conv2_block2_out False
29 conv2_block3_1_conv False
30 conv2_block3_1_bn False
31 conv2_block3_1_relu False
32 conv2_block3_2_conv False
33 conv2_block3_2_bn False
34 conv2_block3_2_relu False
35 conv2_block3_3_conv False
36 conv2_block3_3_bn False
37 conv2_block3_add False
38 conv2_bloc

In [ ]:
def model2():
    input_shape = (224, 224, 3)

    base_model = ResNet50(
        include_top=False,
        weights='imagenet',
        input_shape=input_shape
    )
    # เพิ่มโค้ดนี้ในฟังก์ชัน cor() ก่อน return model
    for layer in base_model.layers:
        layer.trainable = True
        
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(128)(x)
    embedding = Lambda(lambda x: tf.math.l2_normalize(x, axis=1))(x)
    
    # สร้างโมเดลและ return
    model = Model(inputs=base_model.input, outputs=embedding)
    
    return model

In [16]:

def model3():
    input_shape = (224, 224, 3)

    base_model = ResNet50(
        include_top=False,
        weights='imagenet',
        input_shape=input_shape
    )
    
    for layer in base_model.layers:
        layer.trainable = False
    
    for layer in base_model.layers[-30:]:
        layer.trainable = True

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(128)(x)
    embedding = Lambda(lambda x: tf.math.l2_normalize(x, axis=1))(x)
    
    # สร้างโมเดลและ return
    model = Model(inputs=base_model.input, outputs=embedding)
    
    return model

In [17]:
model = model3()
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                              

In [18]:
for i, layer in enumerate(model.layers):
    print(i, layer.name, layer.trainable)

0 input_1 False
1 conv1_pad False
2 conv1_conv False
3 conv1_bn False
4 conv1_relu False
5 pool1_pad False
6 pool1_pool False
7 conv2_block1_1_conv False
8 conv2_block1_1_bn False
9 conv2_block1_1_relu False
10 conv2_block1_2_conv False
11 conv2_block1_2_bn False
12 conv2_block1_2_relu False
13 conv2_block1_0_conv False
14 conv2_block1_3_conv False
15 conv2_block1_0_bn False
16 conv2_block1_3_bn False
17 conv2_block1_add False
18 conv2_block1_out False
19 conv2_block2_1_conv False
20 conv2_block2_1_bn False
21 conv2_block2_1_relu False
22 conv2_block2_2_conv False
23 conv2_block2_2_bn False
24 conv2_block2_2_relu False
25 conv2_block2_3_conv False
26 conv2_block2_3_bn False
27 conv2_block2_add False
28 conv2_block2_out False
29 conv2_block3_1_conv False
30 conv2_block3_1_bn False
31 conv2_block3_1_relu False
32 conv2_block3_2_conv False
33 conv2_block3_2_bn False
34 conv2_block3_2_relu False
35 conv2_block3_3_conv False
36 conv2_block3_3_bn False
37 conv2_block3_add False
38 conv2_bloc

In [19]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)

In [20]:
def triplet_loss(anchor, positive, negative, alpha=0.2):
    epsilon = 1e-8
    
    # คำนวณระยะห่างแบบ Euclidean squared
    pos_dist = tf.reduce_sum(tf.square(anchor - positive), axis=1)
    neg_dist = tf.reduce_sum(tf.square(anchor - negative), axis=1)
    
    # เพิ่ม epsilon และใช้ tf.clip_by_value เพื่อป้องกันค่าผิดปกติ
    pos_dist = tf.clip_by_value(pos_dist, epsilon, 10.0)
    neg_dist = tf.clip_by_value(neg_dist, epsilon, 10.0)
    
    # คำนวณ basic loss
    basic_loss = pos_dist - neg_dist + alpha
    
    # ใช้ tf.nn.relu แทน tf.maximum
    loss = tf.reduce_mean(tf.nn.relu(basic_loss))
    
    # ตรวจสอบ NaN
    loss = tf.where(tf.math.is_finite(loss), loss, tf.constant(0.0))
    
    return loss


In [21]:
import tensorflow as tf

def losshard_mining(anchor, positive, negative, alpha=0.2):
    """
    Computes Triplet Loss with Hard Triplet Mining.
    """
    # 1. Calculate squared Euclidean distances
    pos_dist = tf.reduce_sum(tf.square(anchor - positive), axis=1)
    neg_dist = tf.reduce_sum(tf.square(anchor - negative), axis=1)

    # 2. Find all valid triplets in the batch
    all_triplets = pos_dist - neg_dist + alpha
    
    # 3. Filter out the easy triplets (loss <= 0)
    hard_triplets = tf.where(all_triplets > 0, all_triplets, tf.zeros_like(all_triplets))

    # 4. Take the mean of the hard triplets
    # Add a small value to the denominator to avoid division by zero
    num_hard_triplets = tf.reduce_sum(tf.cast(hard_triplets > 0, dtype=tf.float32))
    
    # Check if there are any hard triplets. If not, the loss is 0
    if num_hard_triplets > 0:
        loss = tf.reduce_sum(hard_triplets) / num_hard_triplets
    else:
        loss = tf.constant(0.0)

    # Return the loss
    return loss

In [22]:
@tf.function
def triplet_loss_val(anchor, positive, negative, alpha=0.2):
    epsilon = 1e-8
    
    # คำนวณระยะห่างแบบ Euclidean squared
    pos_dist = tf.reduce_sum(tf.square(anchor - positive), axis=1)
    neg_dist = tf.reduce_sum(tf.square(anchor - negative), axis=1)
    
    # เพิ่ม epsilon และใช้ tf.clip_by_value เพื่อป้องกันค่าผิดปกติ
    pos_dist = tf.clip_by_value(pos_dist, epsilon, 10.0)
    neg_dist = tf.clip_by_value(neg_dist, epsilon, 10.0)
    
    # คำนวณ basic loss
    basic_loss = pos_dist - neg_dist + alpha
    
    # ใช้ tf.nn.relu แทน tf.maximum
    loss = tf.reduce_mean(tf.nn.relu(basic_loss))
    
    # ตรวจสอบ NaN
    loss = tf.where(tf.math.is_finite(loss), loss, tf.constant(0.0))
    
    return loss

In [23]:
@tf.function
def train_step(anchor, positive, negative):
    with tf.GradientTape() as tape:
        anchor_embedding = model(anchor, training=True)
        positive_embedding = model(positive, training=True)
        negative_embedding = model(negative, training=True)
        loss = triplet_loss(anchor_embedding, positive_embedding, negative_embedding)
    
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss

In [24]:
EPOCHS = 50
print("--- เริ่มการฝึกโมเดล ---")
train_loss_history = []
val_loss_history = []
for epoch in range(EPOCHS):
    total_loss = 0.0
    num_batches = 0
    
    # วนลูปใน training dataset
    print(f"\n--- Epoch {epoch+1}/{EPOCHS} ---")
    for anchor, positive, negative in train_dataset:
        loss = train_step(anchor, positive, negative)
        total_loss += loss
        num_batches += 1
        
        # ปริ้นท์
        if num_batches % 5000 == 0:
            print(f"Batch {num_batches}, Training Loss: {loss.numpy():.4f}")
    
    avg_loss = total_loss / num_batches if num_batches > 0 else 0
    print(f"\nสรุป Epoch {epoch+1}/{EPOCHS}, Training Loss เฉลี่ย: {avg_loss.numpy():.4f}")
    train_loss_history.append(avg_loss)
    # Optional: ตรวจสอบ Validation Loss ในแต่ละ Epoch
    val_total_loss = 0.0
    val_num_batches = 0
    
    # วนลูปใน validation dataset
    print("\n--- เริ่ม Validation ---")
    for anchor, positive, negative in val_dataset:
        anchor_embedding = model(anchor, training=False)
        positive_embedding = model(positive, training=False)
        negative_embedding = model(negative, training=False)
        val_loss = triplet_loss(anchor_embedding, positive_embedding, negative_embedding)
        val_total_loss += val_loss
        val_num_batches += 1
        
        # ปริ้นท์ Val
        if val_num_batches % 500 == 0:
             print(f"Validation Batch {val_num_batches}, Validation Loss: {val_loss.numpy():.4f}")
             
    val_avg_loss = val_total_loss / val_num_batches if val_num_batches > 0 else 0
    print(f"สรุป Validation Loss เฉลี่ย: {val_avg_loss.numpy():.4f}")
    val_loss_history.append(val_avg_loss)
    nameModel = f"modelR{epoch+1}.h5"
    model.save(nameModel)

plt.figure(figsize=(10, 6))
plt.plot(range(1, EPOCHS + 1), train_loss_history, 'o-', label='Training Loss',color='red')
plt.plot(range(1, EPOCHS + 1), val_loss_history, 'x-', label='Validation Loss',color="#00FF2A")
plt.title('Training vs. Validation Loss Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

print("\n--- การฝึกโมเดลเสร็จสิ้น ---")
model.save("2M.h5")


--- เริ่มการฝึกโมเดล ---

--- Epoch 1/50 ---
Batch 5000, Training Loss: 0.2036
Batch 10000, Training Loss: 0.2428

สรุป Epoch 1/50, Training Loss เฉลี่ย: 0.1830

--- เริ่ม Validation ---
Validation Batch 500, Validation Loss: 0.0334
Validation Batch 1000, Validation Loss: 0.2075
สรุป Validation Loss เฉลี่ย: 0.1612

--- Epoch 2/50 ---
Batch 5000, Training Loss: 0.1759
Batch 10000, Training Loss: 0.1930

สรุป Epoch 2/50, Training Loss เฉลี่ย: 0.1515

--- เริ่ม Validation ---
Validation Batch 500, Validation Loss: 0.0905
Validation Batch 1000, Validation Loss: 0.1803
สรุป Validation Loss เฉลี่ย: 0.1340

--- Epoch 3/50 ---
Batch 5000, Training Loss: 0.0841
Batch 10000, Training Loss: 0.0045

สรุป Epoch 3/50, Training Loss เฉลี่ย: 0.1230

--- เริ่ม Validation ---
Validation Batch 500, Validation Loss: 0.0651
Validation Batch 1000, Validation Loss: 0.0000
สรุป Validation Loss เฉลี่ย: 0.1209

--- Epoch 4/50 ---
Batch 5000, Training Loss: 0.0743
Batch 10000, Training Loss: 0.1211

สรุป Epoch 4

KeyboardInterrupt: 

In [ ]:
import tensorflow as tf

def hard_mining(anchor, positive, negative, alpha=0.2):
    pos_dist = tf.reduce_sum(tf.square(anchor - positive), axis=1)
    neg_dist = tf.reduce_sum(tf.square(anchor - negative), axis=1)
    hardest_pos_dist = tf.reduce_max(pos_dist)
    hardest_neg_dist = tf.reduce_min(neg_dist)
    basic_loss = hardest_pos_dist - hardest_neg_dist + alpha
    loss = tf.nn.relu(basic_loss)
    return loss